name: Pytest (PR Entry)

on:
  pull_request_target:
    branches:
      - master

jobs:
  detect-fork:
    runs-on: ubuntu-latest
    outputs:
      is_fork: ${{ steps.check.outputs.is_fork }}
    steps:
      - id: check
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" || "${{ github.event_name }}" == "pull_request_target" ]]; then
            if [[ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]]; then
              echo "is_fork=true" >> $GITHUB_OUTPUT
            else
              echo "is_fork=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "is_fork=false" >> $GITHUB_OUTPUT
          fi

  call-sandbox:
    if: needs.detect-fork.outputs.is_fork == 'true'
    needs: detect-fork
    uses: ./.github/workflows/pytest-core.yaml
    with:
      environment: sandbox-ci
    secrets:
      NPSSO_CODE: ${{ secrets.NPSSO_CODE }}

  call-trusted:
    if: needs.detect-fork.outputs.is_fork == 'false'
    needs: detect-fork
    uses: ./.github/workflows/pytest-core.yaml
    with:
      environment: trusted-ci
    secrets:
      NPSSO_CODE: ${{ secrets.NPSSO_CODE }}
