name: Core Pytest CI

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      NPSSO_CODE:
        required: true
    vars:
      USER_NAME:
        required: true
      FRIEND_USER_NAME:
        required: true
      BLOCKED_USER_NAME:
        required: true

jobs:
  pytest-core:
    runs-on: ${{ matrix.os }}-latest
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }} ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies and build package
        run: poetry install --with tests

      - name: Test with pytest
        run: poetry run python pre_push.py -nu
        env:
          NPSSO_CODE: ${{ secrets.NPSSO_CODE }}
          USER_NAME: ${{ vars.USER_NAME }}
          FRIEND_USER_NAME: ${{ vars.FRIEND_USER_NAME }}
          BLOCKED_USER_NAME: ${{ vars.BLOCKED_USER_NAME }}
