name: Pytest (PR Entry)

on:
  push:
    branches:
      - fix-cicd-from-fork
  pull_request_target:
    branches:
      - master

jobs:
  detect-fork:
    runs-on: ubuntu-latest
    outputs:
      is_fork: ${{ steps.check.outputs.is_fork }}
    steps:
      - id: check
        run: |
          echo "is_fork=$([[ '${{ github.event.pull_request.head.repo.full_name }}' != '${{ github.repository }}' ]] && echo true || echo false)" >> $GITHUB_OUTPUT

  call-sandbox:
    if: needs.detect-fork.outputs.is_fork == 'true'
    needs: detect-fork
    uses: ./.github/workflows/pytest-core.yaml
    with:
      environment: sandbox-ci
      USER_NAME: ${{ vars.USER_NAME }}
      FRIEND_USER_NAME: ${{ vars.FRIEND_USER_NAME }}
      BLOCKED_USER_NAME: ${{ vars.BLOCKED_USER_NAME }}
    secrets:
      NPSSO_CODE: ${{ secrets.NPSSO_CODE }}

  call-trusted:
    if: needs.detect-fork.outputs.is_fork == 'false'
    needs: detect-fork
    uses: ./.github/workflows/pytest-core.yaml
    with:
      environment: trusted-ci
      USER_NAME: ${{ vars.USER_NAME }}
      FRIEND_USER_NAME: ${{ vars.FRIEND_USER_NAME }}
      BLOCKED_USER_NAME: ${{ vars.BLOCKED_USER_NAME }}
    secrets:
      NPSSO_CODE: ${{ secrets.NPSSO_CODE }}
